name: Publish Python Package to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false
        default: ''

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build flake8 black isort
        pip install -e .[test]
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting
      run: |
        black --check .
        isort --check-only .
    
    - name: Run tests
      run: |
        pytest outkast/tests/
    
    - name: Build package
      run: python -m build
    
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
